### ISSUE TITLE
Fails to upload over BLE using Zephyr with SMP Server Sample

### ISSUE THREAD

**Issue by caco3** [apache/mynewt-mcumgr-cli#15]
This is a redirect from https://github.com/zephyrproject-rtos/zephyr/issues/27331
Hi all

I am trying to get the "SMP Server Sample" (https://docs.zephyrproject.org/latest/samples/subsys/mgmt/mcumgr/smp_svr/README.html) working.

I have a nrf52840dongle_nrf52840 and successfully installed MCUboot (option # 2) and the "SMP Server Sample" on it.
I also have a laptop with a built-in BLE radio.
I successfully can test the connection and even list the image:
```
> mcumgr --conntype ble --connstring ctlr_name= peer_name='Zephyr' echo hello 
hello
```
```
> sudo mcumgr --conntype ble --connstring ctlr_name=peer_name='Zephyr' image list
 Images:
  image=0 slot=0
    version: 0.0.0
    bootable: true
    flags: active confirmed
    hash: 37a4a9403fbd0a0336152646947ccce5faf6674e3a29b4220eb2b97a2f613b9d
Split status: N/A (0)
```

How ever when I try to upload a new image, I run into an error:
```
> sudo mcumgr --conntype ble --connstring peer_name='Zephyr' image upload smp_svr.signed.bin -t 100
 0 B / 182.61 KiB [--------------------------------------------------------------------------------------------------]   0.00%
 panic: send on closed channel
 goroutine 493 [running]:
  mynewt.apache.org/newtmgr/nmxact/nmp.(*Listener).AfterTimeout.func1()
    /home/ubuntu/go/src/mynewt.apache.org/newtmgr/nmxact/nmp/dispatch.go:50 +0x64
  created by time.goFunc
    /usr/lib/go-1.13/src/time/sleep.go:168 +0x44
```
In https://github.com/zephyrproject-rtos/zephyr/issues/27331#issuecomment-668104750 I was told to try newtmg, but it has the same outcome:
```
> newtmgr version
Apache Newtmgr 1.9.0-dev


> newtmgr --conntype ble --connstring ctlr_name=hci0,peer_name='Zephyr' image list
Images:
 image=0 slot=0
    version: 0.0.0
    bootable: true
    flags: active confirmed
    hash: 7e9e880e16a42a2494180d6f28de7e8fb44500ac889c4098d074b7d99cabfea3
Split status: N/A (0)


> newtmgr --conntype ble --connstring ctlr_name=hci0,peer_name='Zephyr' image upload /home/<user>/zephyrproject/build/zephyr/zephyr.signed.bin -t 60

 0 B / 182.84 KiB [-----------------------------------------------------------]   0.00%
panic: send on closed channel

goroutine 519 [running]:
mynewt.apache.org/newtmgr/nmxact/nmp.(*Listener).AfterTimeout.func1()
        /home/<user>/go/src/mynewt.apache.org/newtmgr/nmxact/nmp/dispatch.go:50 +0x64
created by time.goFunc
        /usr/lib/go-1.13/src/time/sleep.go:168 +0x44
```

Called with `debug` enabled:
```
> newtmgr --conntype ble --connstring ctlr_name=hci0,peer_name='Zephyr' image upload /home/<user>/zephyrproject/build/zephyr/zephyr.signed.bin -t 60 -l "debug"
DEBU[2020-08-03 20:08:32.588] Using connection profile: name=unnamed type=ble connstring=ctlr_name=hci0,peer_name=Zephyr 
DEBU[2020-08-03 20:08:32.827] Connecting to peer                           
DEBU[2020-08-03 20:08:32.94] Exchanging MTU                               
DEBU[2020-08-03 20:08:32.951] Exchanged MTU; ATT MTU = 252                 
DEBU[2020-08-03 20:08:32.951] Discovering profile                          
DEBU[2020-08-03 20:08:33.093] Subscribing to NMP response characteristic   
 0 / 187228 [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%DEBU[2020-08-03 20:08:33.111] Encoded &{NmpBase:{hdr:{Op:2 Flags:0 Len:0 Group:1 Seq:66 Id:1}} ImageNum:0 Off:0 Len:187228 DataSha:[185 111 70 248 162 92 253 252 155 75 238 215 165 95 9 25 33 110 108 0 163 113 251 87 208 38 149 239 126 230 35 102] Upgrade:false Data:[61 184 243 150 0 0 0 0 0 2 0 0 12 216 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} to:
00000000  a5 64 64 61 74 61 59 02  00 3d b8 f3 96 00 00 00  |.ddataY..=......|
00000010  00 00 02 00 00 0c d8 02  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000100  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000140  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000150  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000160  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000170  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000180  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000190  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000200  00 00 00 00 00 00 00 00  00 65 69 6d 61 67 65 00  |.........eimage.|
00000210  63 6c 65 6e 1a 00 02 db  5c 63 6f 66 66 00 63 73  |clen....\coff.cs|
00000220  68 61 58 20 b9 6f 46 f8  a2 5c fd fc 9b 4b ee d7  |haX .oF..\...K..|
00000230  a5 5f 09 19 21 6e 6c 00  a3 71 fb 57 d0 26 95 ef  |._..!nl..q.W.&..|
00000240  7e e6 23 66                                       |~.#f| 
DEBU[2020-08-03 20:08:33.111] Encoded:
00000000  02 00 02 44 00 01 42 01  a5 64 64 61 74 61 59 02  |...D..B..ddataY.|
00000010  00 3d b8 f3 96 00 00 00  00 00 02 00 00 0c d8 02  |.=..............|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000100  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000140  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000150  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000160  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000170  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000180  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000190  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000200  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000210  00 65 69 6d 61 67 65 00  63 6c 65 6e 1a 00 02 db  |.eimage.clen....|
00000220  5c 63 6f 66 66 00 63 73  68 61 58 20 b9 6f 46 f8  |\coff.cshaX .oF.|
00000230  a2 5c fd fc 9b 4b ee d7  a5 5f 09 19 21 6e 6c 00  |.\...K..._..!nl.|
00000240  a3 71 fb 57 d0 26 95 ef  7e e6 23 66              |.q.W.&..~.#f| 
DEBU[2020-08-03 20:08:33.111] Encoded &{NmpBase:{hdr:{Op:2 Flags:0 Len:0 Group:1 Seq:66 Id:1}} ImageNum:0 Off:0 Len:187228 DataSha:[185 111 70 248 162 92 253 252 155 75 238 215 165 95 9 25 33 110 108 0 163 113 251 87 208 38 149 239 126 230 35 102] Upgrade:false Data:[61 184 243 150 0 0 0 0 0 2 0 0 12 216 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} to:
00000000  a5 64 64 61 74 61 58 ad  3d b8 f3 96 00 00 00 00  |.ddataX.=.......|
00000010  00 02 00 00 0c d8 02 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 65 69 6d  61 67 65 00 63 6c 65 6e  |.....eimage.clen|
000000c0  1a 00 02 db 5c 63 6f 66  66 00 63 73 68 61 58 20  |....\coff.cshaX |
000000d0  b9 6f 46 f8 a2 5c fd fc  9b 4b ee d7 a5 5f 09 19  |.oF..\...K..._..|
000000e0  21 6e 6c 00 a3 71 fb 57  d0 26 95 ef 7e e6 23 66  |!nl..q.W.&..~.#f| 
DEBU[2020-08-03 20:08:33.111] Encoded:
00000000  02 00 00 f0 00 01 42 01  a5 64 64 61 74 61 58 ad  |......B..ddataX.|
00000010  3d b8 f3 96 00 00 00 00  00 02 00 00 0c d8 02 00  |=...............|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 65 69 6d  |.............eim|
000000c0  61 67 65 00 63 6c 65 6e  1a 00 02 db 5c 63 6f 66  |age.clen....\cof|
000000d0  66 00 63 73 68 61 58 20  b9 6f 46 f8 a2 5c fd fc  |f.cshaX .oF..\..|
000000e0  9b 4b ee d7 a5 5f 09 19  21 6e 6c 00 a3 71 fb 57  |.K..._..!nl..q.W|
000000f0  d0 26 95 ef 7e e6 23 66                           |.&..~.#f| 

[..]


DEBU[2020-08-03 20:08:36.128] {add-nmp-listener} [bll_sesn.go:412] seq=28  
DEBU[2020-08-03 20:08:36.128] Encoded &{NmpBase:{hdr:{Op:2 Flags:0 Len:0 Group:1 Seq:28 Id:1}} ImageNum:0 Off:47480 Len:0 DataSha:[] Upgrade:false Data:[32 49 23 240 16 191 0 191 201 221 1 0 7 181 8 56 1 144 1 169 2 72 19 240 253 249 3 176 93 248 4 251 236 9 0 32 240 181 133 176 14 104 5 70 12 70 0 39 79 244 32 83 0 104 141 248 8 112 2 169 173 248 10 48 23 240 238 251 160 177 66 246 1 3 40 104 141 248 12 112 3 169 173 248 14 48 23 240 227 251 72 177 35 105 35 177 42 138 89 136 145 66 0 210 90 128 1 32 5 176 240 189 97 104 40 104 23 240 212 251 16 177 0 35 35 97 244 231 227 104 160 104 26 120 58 177 182 248 94 48 129 137 91 26 147 66 1 218 0 32 233 231 4 33 8 48 25 240 162 249 43 138 32 97 3 128 67 128 7 75 0 147 162 104 1 148 0 35 41 70 48 70 23 240 6 255 0 40 234 219 32 105 0 56 24 191 1 32 209 231 239 89 3 0 45 233 243 65 209 248 0 128 6 70 12 70 0 104]} to:
00000000  a3 64 64 61 74 61 58 da  20 31 17 f0 10 bf 00 bf  |.ddataX. 1......|
00000010  c9 dd 01 00 07 b5 08 38  01 90 01 a9 02 48 13 f0  |.......8.....H..|
00000020  fd f9 03 b0 5d f8 04 fb  ec 09 00 20 f0 b5 85 b0  |....]...... ....|
00000030  0e 68 05 46 0c 46 00 27  4f f4 20 53 00 68 8d f8  |.h.F.F.'O. S.h..|
00000040  08 70 02 a9 ad f8 0a 30  17 f0 ee fb a0 b1 42 f6  |.p.....0......B.|
00000050  01 03 28 68 8d f8 0c 70  03 a9 ad f8 0e 30 17 f0  |..(h...p.....0..|
00000060  e3 fb 48 b1 23 69 23 b1  2a 8a 59 88 91 42 00 d2  |..H.#i#.*.Y..B..|
00000070  5a 80 01 20 05 b0 f0 bd  61 68 28 68 17 f0 d4 fb  |Z.. ....ah(h....|
00000080  10 b1 00 23 23 61 f4 e7  e3 68 a0 68 1a 78 3a b1  |...##a...h.h.x:.|
00000090  b6 f8 5e 30 81 89 5b 1a  93 42 01 da 00 20 e9 e7  |..^0..[..B... ..|
000000a0  04 21 08 30 19 f0 a2 f9  2b 8a 20 61 03 80 43 80  |.!.0....+. a..C.|
000000b0  07 4b 00 93 a2 68 01 94  00 23 29 46 30 46 17 f0  |.K...h...#)F0F..|
000000c0  06 ff 00 28 ea db 20 69  00 38 18 bf 01 20 d1 e7  |...(.. i.8... ..|
000000d0  ef 59 03 00 2d e9 f3 41  d1 f8 00 80 06 46 0c 46  |.Y..-..A.....F.F|
000000e0  00 68 65 69 6d 61 67 65  00 63 6f 66 66 19 b9 78  |.heimage.coff..x| 
DEBU[2020-08-03 20:08:36.128] Encoded:
00000000  02 00 00 f0 00 01 1c 01  a3 64 64 61 74 61 58 da  |.........ddataX.|
00000010  20 31 17 f0 10 bf 00 bf  c9 dd 01 00 07 b5 08 38  | 1.............8|
00000020  01 90 01 a9 02 48 13 f0  fd f9 03 b0 5d f8 04 fb  |.....H......]...|
00000030  ec 09 00 20 f0 b5 85 b0  0e 68 05 46 0c 46 00 27  |... .....h.F.F.'|
00000040  4f f4 20 53 00 68 8d f8  08 70 02 a9 ad f8 0a 30  |O. S.h...p.....0|
00000050  17 f0 ee fb a0 b1 42 f6  01 03 28 68 8d f8 0c 70  |......B...(h...p|
00000060  03 a9 ad f8 0e 30 17 f0  e3 fb 48 b1 23 69 23 b1  |.....0....H.#i#.|
00000070  2a 8a 59 88 91 42 00 d2  5a 80 01 20 05 b0 f0 bd  |*.Y..B..Z.. ....|
00000080  61 68 28 68 17 f0 d4 fb  10 b1 00 23 23 61 f4 e7  |ah(h.......##a..|
00000090  e3 68 a0 68 1a 78 3a b1  b6 f8 5e 30 81 89 5b 1a  |.h.h.x:...^0..[.|
000000a0  93 42 01 da 00 20 e9 e7  04 21 08 30 19 f0 a2 f9  |.B... ...!.0....|
000000b0  2b 8a 20 61 03 80 43 80  07 4b 00 93 a2 68 01 94  |+. a..C..K...h..|
000000c0  00 23 29 46 30 46 17 f0  06 ff 00 28 ea db 20 69  |.#)F0F.....(.. i|
000000d0  00 38 18 bf 01 20 d1 e7  ef 59 03 00 2d e9 f3 41  |.8... ...Y..-..A|
000000e0  d1 f8 00 80 06 46 0c 46  00 68 65 69 6d 61 67 65  |.....F.F.heimage|
000000f0  00 63 6f 66 66 19 b9 78                           |.coff..x| 
DEBU[2020-08-03 20:08:36.128] Tx NMP async request: seq 28 00000000  02 00 00 f0 00 01 1c 01  a3 64 64 61 74 61 58 da  |.........ddataX.|
00000010  20 31 17 f0 10 bf 00 bf  c9 dd 01 00 07 b5 08 38  | 1.............8|
00000020  01 90 01 a9 02 48 13 f0  fd f9 03 b0 5d f8 04 fb  |.....H......]...|
00000030  ec 09 00 20 f0 b5 85 b0  0e 68 05 46 0c 46 00 27  |... .....h.F.F.'|
00000040  4f f4 20 53 00 68 8d f8  08 70 02 a9 ad f8 0a 30  |O. S.h...p.....0|
00000050  17 f0 ee fb a0 b1 42 f6  01 03 28 68 8d f8 0c 70  |......B...(h...p|
00000060  03 a9 ad f8 0e 30 17 f0  e3 fb 48 b1 23 69 23 b1  |.....0....H.#i#.|
00000070  2a 8a 59 88 91 42 00 d2  5a 80 01 20 05 b0 f0 bd  |*.Y..B..Z.. ....|
00000080  61 68 28 68 17 f0 d4 fb  10 b1 00 23 23 61 f4 e7  |ah(h.......##a..|
00000090  e3 68 a0 68 1a 78 3a b1  b6 f8 5e 30 81 89 5b 1a  |.h.h.x:...^0..[.|
000000a0  93 42 01 da 00 20 e9 e7  04 21 08 30 19 f0 a2 f9  |.B... ...!.0....|
000000b0  2b 8a 20 61 03 80 43 80  07 4b 00 93 a2 68 01 94  |+. a..C..K...h..|
000000c0  00 23 29 46 30 46 17 f0  06 ff 00 28 ea db 20 69  |.#)F0F.....(.. i|
000000d0  00 38 18 bf 01 20 d1 e7  ef 59 03 00 2d e9 f3 41  |.8... ...Y..-..A|
000000e0  d1 f8 00 80 06 46 0c 46  00 68 65 69 6d 61 67 65  |.....F.F.heimage|
000000f0  00 63 6f 66 66 19 b9 78                           |.coff..x| 
panic: send on closed channel

goroutine 475 [running]:
mynewt.apache.org/newtmgr/nmxact/nmp.(*Listener).AfterTimeout.func1()
        /home/<user>/go/src/mynewt.apache.org/newtmgr/nmxact/nmp/dispatch.go:50 +0x64
created by time.goFunc
        /usr/lib/go-1.13/src/time/sleep.go:168 +0x44
```

The upload call always fails after around 3.5 seconds with the mentioned error.
Looking on the devices log, I only get:
```
    *** Booting Zephyr OS build zephyr-v2.3.0-1533-gdc48999ee163  ***
    [00:00:00.004,760] <inf> mcuboot: Starting bootloader
    [00:00:00.005,310] <inf> mcuboot: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, 3
    [00:00:00.005,340] <inf> mcuboot: Boot source: none
    [00:00:00.005,401] <inf> mcuboot: Swap type: none
   
    *** Booting Zephyr OS build zephyr-v2.3.0-1533-gdc48999ee163  ***
    [00:00:00.006,134] <inf> littlefs: LittleFS version 2.2, disk version 2.0
    [00:00:00.006,347] <inf> littlefs: FS at NRF_FLASH_DRV_NAME:0xfc000 is 4 0x1000-byte blocks e
    [00:00:00.006,347] <inf> littlefs: sizes: rd 16 ; pr 16 ; ca 64 ; la 32
    [00:00:00.006,591] <inf> littlefs: /lfs mounted
    [00:00:00.008,697] <inf> smp_bt_sample: Bluetooth initialized
    [00:00:00.009,124] <inf> smp_sample: build time: Aug  3 2020 16:39:19
    [00:00:00.034,149] <inf> smp_bt_sample: Advertising successfully started
    [00:00:09.163,452] <inf> smp_bt_sample: Connected
    [00:00:13.067,138] <inf> smp_bt_sample: Disconnected (reason 0x08)
    [00:00:13.068,145] <inf> smp_bt_sample: Advertising successfully started
```

**Comment by caco3** [comment]
@utzig FYI

**Comment by caco3** [comment]
I was now also testing it successfully with the [nRF Connect for Mobile](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp).

So it MUST be a bug related to MCUmgr on the PC side.

**Comment by lawrence-king** [comment]
Try moving the Zephyr target about 15ft away from the laptop. This worked for me (Lenovo laptop with built-in Intel bluetooth chip USB\VID_8087&PID_0A2B&REV_0010).

**Comment by caco3** [comment]
Hi @lawrence-king 

> Try moving the Zephyr target about 15ft away from the laptop. This worked for me (Lenovo laptop with built-in Intel bluetooth chip USB\VID_8087&PID_0A2B&REV_0010).

So you want to say you had the SAME error and you could fix it by moving away 5 meters? That sounds rater odd, because the other commands worked fine, so the BLE link should be ok!

Nevertheless, I tried it 😄 but had sadly no improvements 😒

**Comment by lawrence-king** [comment]
Yes this did work for me, same problem, however there are many other variables involved (windows version, driver for BT adapter, BT adapter chipset, laptop manufacturer, just to name a few).

Sorry to hear it didn’t work for you.

As I mentioned my longer term solution was to not share the BT adapter with the laptop OS.

Lawrence King
Principal Developer
+1(416)627-7302

**Comment by caco3** [comment]
@utzig Can you confirm this issue or is it working on a setup you have?

**Comment by trueb2** [comment]
I am having this issue as well. I am using nrf52dk_nrf52832 with the built-in BLE on a mac book pro. I am using mcumgr installed from ``go get github.com/apache/mynewt-mcumgr-cli/mcumgr`` (https://github.com/apache/mynewt-mcumgr). It appears to be behind the 0.1.0 latest release.

```
user@host ~ % mcumgr version
mcumgr 0.0.0-dev
```

**Comment by trueb2** [comment]
To follow up with the various OTA update options that I have tried.

* I found that the newtmgr (1.9.0-dev) and mcumgr exhibited the same behavior for me as well. 
* As for the [nRF Connect app for iOS](https://apps.apple.com/us/app/nrf-connect/id1054362403), the upload succeeded but one of the test, reset, or confirm failed to successfully perform the upgrade. 
* As for the [nRF Toolbox app for iOS](https://apps.apple.com/us/app/nrf-toolbox/id820906058), the OTA DFU was successful via the MCU Manager utility.

**Comment by kyberdin** [comment]
Also running into this, with the current retrieval from `go get github.com/apache/mynewt-mcumgr-cli/mcumgr` (**mcumgr 0.0.0-dev**).

`image list`, `reset`, and `echo` all work without issue; `image upload` causes the panic.

Confirmed successful DFU via nRF Connect app for iOS and nRF Toolbox app for iOS.

**Comment by caco3** [comment]
> 
> 
> I am having this issue as well. I am using nrf52dk_nrf52832 with the built-in BLE on a mac book pro. I am using mcumgr installed from `go get github.com/apache/mynewt-mcumgr-cli/mcumgr` (https://github.com/apache/mynewt-mcumgr). It appears to be behind the 0.1.0 latest release.
> 
> ```
> user@host ~ % mcumgr version
> mcumgr 0.0.0-dev
> ```


Version `0.0.0-dev` is hard coded: https://github.com/apache/mynewt-mcumgr-cli/blob/master/mcumgr/mcumgr.go#L65

Not sure why @sjanc Tagged it with `0.1.0` in https://github.com/apache/mynewt-mcumgr/releases/tag/mcumgr_0_1_0_tag 
I guess he forgot to updated the hardcoded value.

**Comment by utzig** [comment]
> @utzig Can you confirm this issue or is it working on a setup you have?

My nrf-52x boards are currently not working, so no.

> > I am having this issue as well. I am using nrf52dk_nrf52832 with the built-in BLE on a mac book pro. I am using mcumgr installed from `go get github.com/apache/mynewt-mcumgr-cli/mcumgr` (https://github.com/apache/mynewt-mcumgr). It appears to be behind the 0.1.0 latest release.
> > ```
> > user@host ~ % mcumgr version
> > mcumgr 0.0.0-dev
> > ```
> 
> Version `0.0.0-dev` is hard coded: https://github.com/apache/mynewt-mcumgr-cli/blob/master/mcumgr/mcumgr.go#L65
> 
> Not sure why @sjanc Tagged it with `0.1.0` in https://github.com/apache/mynewt-mcumgr/releases/tag/mcumgr_0_1_0_tag
> I guess he forgot to updated the hardcoded value.

I believe you are confusing `mynewt-mcumgr` and `mynewt-mcumgr-cli`. The first one is a dependency for Mynewt and is tagged; the second one is not and is not tagged (but maybe it should!).

**Comment by caco3** [comment]
@utzig You are right, sry! I was confused that @trueb2 mentioned `0.1.0`.

As to try to troubleshoot it:
Which was the last version you know it worked?
I am not yet into `Go`, but it seems that your `mcumgr.go` does not do that much but instead heavily relies on the `newtmgr` libraries. So I would expect that it broke through an update of those includes.

**Comment by nkaje** [comment]
Could you please check if https://github.com/apache/mynewt-newtmgr/pull/170 resolves this? Thanks @rmal30 for reporting this in newtmgr.

**Comment by caco3** [comment]
Thanks for your work!
I am currently on holiday and will test it in 2 weeks.

**Comment by caco3** [comment]
I can confirm that this got fixed now with https://github.com/apache/mynewt-newtmgr/pull/170.

Thank you all for your work!
