### ISSUE TITLE
Progress bar panic in Yocto

### ISSUE THREAD

**Issue by antanas-v** [apache/mynewt-mcumgr-cli#23]
Hi
running mcumgr-cli on ARM Yocto system results in panic. The same latest code runs OK on Linux PC. Seems to be related to progress bar. The embedded system uses 'sh' shell, the crash is reproducible 100% with both ssh and serial terminal.

```
# mcumgr --conntype serial --connstring="/dev/ttyUSB0,baud=921600"  image upload signed.bin
 10.91 KiB / 78.32 KiB   13.93% 2.98 KiB/s 00m22spanic: runtime error: invalid memory address or nil pointer dereference--------------------------------------------------------------------------------------------------------------------------------------------]   7.57% 2.65 KiB/s 00m27s
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x764bdb24]

goroutine 11 [running]:
regexp.(*Regexp).allMatches(0x45676370, 0x45884100, 0x33, 0x0, 0x0, 0x0, 0x34, 0x45623cb4)
	/usr/lib/go/src/regexp/regexp.go:719 +0xb8
regexp.(*Regexp).FindAllString(0x45676370, 0x45884100, 0x33, 0xffffffff, 0x0, 0x8, 0x0)
	/usr/lib/go/src/regexp/regexp.go:1060 +0xa4
github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb%2ev1.escapeAwareRuneCountInString(0x45884100, 0x33, 0x9)
	/home/antanas/yocto/build-apalis-imx6/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/mynewt-mcumgr-cli/1.0-r0/build/src/github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb.v1/runecount.go:13 +0x74
github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).write(0x457341c0, 0x1394c, 0x0, 0x30f7, 0x0)
	/home/antanas/yocto/build-apalis-imx6/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/mynewt-mcumgr-cli/1.0-r0/build/src/github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb.v1/pb.go:358 +0x478
github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Update(0x457341c0)
	/home/antanas/yocto/build-apalis-imx6/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/mynewt-mcumgr-cli/1.0-r0/build/src/github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb.v1/pb.go:455 +0xc4
github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).refresher(0x457341c0)
	/home/antanas/yocto/build-apalis-imx6/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/mynewt-mcumgr-cli/1.0-r0/build/src/github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb.v1/pb.go:503 +0x20
created by github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Start
	/home/antanas/yocto/build-apalis-imx6/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/mynewt-mcumgr-cli/1.0-r0/build/src/github.com/apache/mynewt-mcumgr-cli/vendor/gopkg.in/cheggaaa/pb.v1/pb.go:124 +0xf8
```

**Comment by antanas-v** [comment]
works OK when cross compiled without Yocto. Build system issue
