### ISSUE TITLE
MACos - Echo hello returns error: Failed to connect to peer after 10sec

### ISSUE THREAD

**Issue by markusarnoldsson** [apache/mynewt-mcumgr-cli#27]
Hello!

I am using the SMP Server sample from Zephyr on a nRF52DK. I can send echo command through nRF Device Manager successfully.

However, doing it on MAC returns: Failed to connect to peer after 10sec.

I am using this command: 
`sudo ./mcumgr --conntype ble --connstring peer_name='Zephyr' echo hello`

I am using Go version 17 and installed mcumgr by writing:
`go get github.com/apache/mynewt-mcumgr-cli/mcumgr`

Any idea what the reason could be?

**Comment by markusarnoldsson** [comment]
Using --loglevel debug prints this:
`markusarnoldsson@Markuss-MacBook-Air ~ % sudo go/bin/mcumgr --loglevel debug --conntype ble --connstring ctlr_name=hci0,peer_name='Zephyr' echo hello

DEBU[2022-05-02 17:19:41.851] Using connection profile: name=unnamed type=ble connstring=ctlr_name=hci0,peer_name=Zephyr 

DEBU[2022-05-02 17:19:41.898] CentralManagerDidUpdateState: cmgr=0x6000030003f0 

DEBU[2022-05-02 17:19:41.912] PeripheralManagerDidUpdateState: pmgr=0x600003504000 

DEBU[2022-05-02 17:19:41.912] Connecting to peer                           

DEBU[2022-05-02 17:19:51.914] goroutine 1 [running]:

mynewt.apache.org/newt/util.NewNewtError({0xc0002261e0, 0x23})

/Users/markusarnoldsson/go/pkg/mod/mynewt.apache.org/newt@v0.0.0-20201028015609-b57111dbd19f/util/util.go:77 +0xc5

mynewt.apache.org/newt/util.ChildNewtError({0x44e4080, 0xc00020c2e0})

/Users/markusarnoldsson/go/pkg/mod/mynewt.apache.org/newt@v0.0.0-20201028015609-b57111dbd19f/util/util.go:103 +0x6b

mynewt.apache.org/newtmgr/newtmgr/cli.GetSesn()

/Users/markusarnoldsson/go/pkg/mod/mynewt.apache.org/newtmgr@v0.0.0-20201028150837-60b2da78788c/newtmgr/cli/common.go:339 +0x1f8

mynewt.apache.org/newtmgr/newtmgr/cli.echoRunCmd(0xc00025a000, {0xc000260000, 0x1, 0xc})

/Users/markusarnoldsson/go/pkg/mod/mynewt.apache.org/newtmgr@v0.0.0-20201028150837-60b2da78788c/newtmgr/cli/echo.go:37 +0x4a

github.com/spf13/cobra.(*Command).execute(0xc00025a000, {0xc00025e000, 0x7, 0xc})

/Users/markusarnoldsson/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x5f8

github.com/spf13/cobra.(*Command).ExecuteC(0xc000224000)

/Users/markusarnoldsson/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc

github.com/spf13/cobra.(*Command).Execute(...)

/Users/markusarnoldsson/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864

main.main()

/Users/markusarnoldsson/go/pkg/mod/github.com/apache/mynewt-mcumgr-cli@v0.0.0-20220314100811-4ca672d31f82/mcumgr/mcumgr.go:94 +0x173


goroutine 20 [syscall]:

os/signal.signal_recv()

/usr/local/go/src/runtime/sigqueue.go:166 +0x28

os/signal.loop()

/usr/local/go/src/os/signal/signal_unix.go:24 +0x19

created by os/signal.Notify.func1.1

/usr/local/go/src/os/signal/signal.go:151 +0x2c


goroutine 34 [chan receive]:

main.main.func1()

/Users/markusarnoldsson/go/pkg/mod/github.com/apache/mynewt-mcumgr-cli@v0.0.0-20220314100811-4ca672d31f82/mcumgr/mcumgr.go:82 +0x38

created by main.main

/Users/markusarnoldsson/go/pkg/mod/github.com/apache/mynewt-mcumgr-cli@v0.0.0-20220314100811-4ca672d31f82/mcumgr/mcumgr.go:80 +0x169 

Error: Failed to connect to peer after 10s`

**Comment by rjain0000** [comment]
I am facing the same issue. 

- at first, mcumgr just killed with -9. Then I found permission issue for BT. 
- after this I get the same error.

Anyluck ?

**Comment by markusarnoldsson** [comment]
Hello!

Sorry no luck. Since I had some time constraints I ended up using a Linux computer instead where it worked as expected.

**Comment by ojousima** [comment]
I just hit the same error, will go to look for a Linux PC
