### ISSUE TITLE
go version issues

### ISSUE THREAD

**Issue by jeffrizzo** [apache/mynewt-mcumgr-cli#30]
Summary: Under MacOS 10.15 (Catalina), x86_64, it won't install with go 1.19 or 1.18 (see below), with go 1.17 it installs, but won't run (see below).  Under go 1.16 (which is deprecated!), things seem to run at least enough to get the "usage" printed out.

```
go version go1.19.1 darwin/amd64
monkeyfist:riz  ~> go install -v github.com/apache/mynewt-mcumgr-cli/mcumgr@latest
go: downloading github.com/apache/mynewt-mcumgr-cli v0.0.0-20220314100811-4ca672d31f82
go: downloading mynewt.apache.org/newtmgr v0.0.0-20201028150837-60b2da78788c
go: downloading mynewt.apache.org/newt v0.0.0-20201028015609-b57111dbd19f
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/JuulLabs-OSS/ble v0.0.0-20200716215611-d4fcc9d598bb
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/sirupsen/logrus v1.5.0
go: downloading github.com/JuulLabs-OSS/cbgo v0.0.1
go: downloading github.com/runtimeco/go-coap v0.0.0-20190911184520-8e5532820fc0
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/cobra v0.0.5
go: downloading gopkg.in/abiosoft/ishell.v2 v2.0.0
go: downloading gopkg.in/cheggaaa/pb.v1 v1.0.28
go: downloading github.com/joaojeronimo/go-crc16 v0.0.0-20140729130949-59bd0194935e
go: downloading github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
go: downloading golang.org/x/net v0.0.0-20191119073136-fc4aabc6c914
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: downloading github.com/ugorji/go v1.1.7
go: downloading github.com/abiosoft/readline v0.0.0-20180607040430-155bce2042db
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: downloading github.com/mattn/go-runewidth v0.0.6
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mgutz/logxi v0.0.0-20161027140823-aebf8a7d67ab
go: downloading github.com/raff/goble v0.0.0-20200327175727-d63360dcfd80
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
golang.org/x/sys/unix
# golang.org/x/sys/unix
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:121:3: too many errors
monkeyfist:riz  ~>
```

```
monkeyfist:riz  ~> go version
go version go1.18.6 darwin/amd64
monkeyfist:riz  ~> go install -v github.com/apache/mynewt-mcumgr-cli/mcumgr@latest
go: downloading github.com/apache/mynewt-mcumgr-cli v0.0.0-20220314100811-4ca672d31f82
go: downloading mynewt.apache.org/newtmgr v0.0.0-20201028150837-60b2da78788c
go: downloading mynewt.apache.org/newt v0.0.0-20201028015609-b57111dbd19f
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/JuulLabs-OSS/ble v0.0.0-20200716215611-d4fcc9d598bb
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/sirupsen/logrus v1.5.0
go: downloading github.com/joaojeronimo/go-crc16 v0.0.0-20140729130949-59bd0194935e
go: downloading github.com/runtimeco/go-coap v0.0.0-20190911184520-8e5532820fc0
go: downloading github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
go: downloading github.com/JuulLabs-OSS/cbgo v0.0.1
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/cobra v0.0.5
go: downloading gopkg.in/abiosoft/ishell.v2 v2.0.0
go: downloading gopkg.in/cheggaaa/pb.v1 v1.0.28
go: downloading golang.org/x/net v0.0.0-20191119073136-fc4aabc6c914
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/fatih/structs v1.1.0
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: downloading github.com/ugorji/go v1.1.7
go: downloading github.com/abiosoft/readline v0.0.0-20180607040430-155bce2042db
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: downloading github.com/mattn/go-runewidth v0.0.6
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mgutz/logxi v0.0.0-20161027140823-aebf8a7d67ab
go: downloading github.com/raff/goble v0.0.0-20200327175727-d63360dcfd80
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
golang.org/x/sys/unix
# golang.org/x/sys/unix
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:121:3: too many errors
monkeyfist:riz  ~>
```

```
monkeyfist:riz  ~> go version
go version go1.17.13 darwin/amd64
monkeyfist:riz  ~> go install -v github.com/apache/mynewt-mcumgr-cli/mcumgr@latest
go: downloading github.com/apache/mynewt-mcumgr-cli v0.0.0-20220314100811-4ca672d31f82
go: downloading mynewt.apache.org/newtmgr v0.0.0-20201028150837-60b2da78788c
go: downloading mynewt.apache.org/newt v0.0.0-20201028015609-b57111dbd19f
go: downloading github.com/JuulLabs-OSS/ble v0.0.0-20200716215611-d4fcc9d598bb
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/sirupsen/logrus v1.5.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/joaojeronimo/go-crc16 v0.0.0-20140729130949-59bd0194935e
go: downloading github.com/runtimeco/go-coap v0.0.0-20190911184520-8e5532820fc0
go: downloading github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
go: downloading github.com/JuulLabs-OSS/cbgo v0.0.1
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/cobra v0.0.5
go: downloading gopkg.in/abiosoft/ishell.v2 v2.0.0
go: downloading gopkg.in/cheggaaa/pb.v1 v1.0.28
go: downloading golang.org/x/net v0.0.0-20191119073136-fc4aabc6c914
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/ugorji/go v1.1.7
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/abiosoft/readline v0.0.0-20180607040430-155bce2042db
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: downloading github.com/mattn/go-runewidth v0.0.6
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mgutz/logxi v0.0.0-20161027140823-aebf8a7d67ab
go: downloading github.com/raff/goble v0.0.0-20200327175727-d63360dcfd80
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
monkeyfist:riz  ~> mcumgr
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff6ca7570a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff6ca7570a
stack: frame={sp:0x7ffeefbff768, fp:0x7ffeefbff7b8} stack=[0x7ffeefb80808,0x7ffeefbff870)
0x00007ffeefbff668:  0x01007ffeefbff688  0x0000000000000004
0x00007ffeefbff678:  0x000000000000001f  0x00007fff6ca7570a
0x00007ffeefbff688:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff698:  0x00000000040360d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff738
0x00007ffeefbff6a8:  0x000000000445fe59  0x00007ffeefbff6f0
0x00007ffeefbff6b8:  0x0000000004036388 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000047cb340
0x00007ffeefbff6c8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff6d8:  0x00007ffeefbff738  0x00000000040360d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff6e8:  0x00000000047cb340  0x00007ffeefbff728
0x00007ffeefbff6f8:  0x0000000004036310 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff708
0x00007ffeefbff708:  0x0000000004036340 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000047cb340
0x00007ffeefbff718:  0x00000000040360d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff738
0x00007ffeefbff728:  0x00007ffeefbff758  0x00000000040360d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff738:  0x00007ffeefbff740  0x0000000004036100 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff748:  0x0000000004465cc6  0x000000000000002a
0x00007ffeefbff758:  0x00007ffeefbff7a8  0x000000000404bc09 <runtime.sigpanic+0x0000000000000389>
0x00007ffeefbff768: <0x0000000004465cc6  0x000000c0001c6000
0x00007ffeefbff778:  0x00007ffeefbff7e8  0x0000000000000000
0x00007ffeefbff788:  0x00000000047cb720  0x0000000000000000
0x00007ffeefbff798:  0x000000c000187738  0x00000000040ade20 <syscall.libc_getpid_trampoline+0x0000000000000000>
0x00007ffeefbff7a8:  0x00007ffeefbff7f0 !0x00007fff6ca7570a
0x00007ffeefbff7b8: >0x00007ffeefbff7f0  0x0000000004784000
0x00007ffeefbff7c8:  0x000000000000032e  0x00000000041169c5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff7d8:  0x0000000004068bbf <runtime.syscall+0x000000000000001f>  0x000000c0001876f0
0x00007ffeefbff7e8:  0x00007ffeefbff830  0x000000c0001876c0
0x00007ffeefbff7f8:  0x0000000004066a30 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff808:  0x000000c0001a6600  0x6600000000000020
0x00007ffeefbff818:  0x0000000000000000  0x000000c0000001a0
0x00007ffeefbff828:  0x0000000000000968  0x000000c0000001a0
0x00007ffeefbff838:  0x0000000004064b49 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff848:  0x00000000044e0678  0x00000000047cb340
0x00007ffeefbff858:  0x00007ffeefbff8a0  0x0000000004064a45 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff868:  0x00000000040649fd <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x4465cc6, 0xc0001c6000})
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff6ca7570a
stack: frame={sp:0x7ffeefbff768, fp:0x7ffeefbff7b8} stack=[0x7ffeefb80808,0x7ffeefbff870)
0x00007ffeefbff668:  0x01007ffeefbff688  0x0000000000000004
0x00007ffeefbff678:  0x000000000000001f  0x00007fff6ca7570a
0x00007ffeefbff688:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff698:  0x00000000040360d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff738
0x00007ffeefbff6a8:  0x000000000445fe59  0x00007ffeefbff6f0
0x00007ffeefbff6b8:  0x0000000004036388 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000047cb340
0x00007ffeefbff6c8:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff6d8:  0x00007ffeefbff738  0x00000000040360d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff6e8:  0x00000000047cb340  0x00007ffeefbff728
0x00007ffeefbff6f8:  0x0000000004036310 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff708
0x00007ffeefbff708:  0x0000000004036340 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000047cb340
0x00007ffeefbff718:  0x00000000040360d1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff738
0x00007ffeefbff728:  0x00007ffeefbff758  0x00000000040360d1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff738:  0x00007ffeefbff740  0x0000000004036100 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff748:  0x0000000004465cc6  0x000000000000002a
0x00007ffeefbff758:  0x00007ffeefbff7a8  0x000000000404bc09 <runtime.sigpanic+0x0000000000000389>
0x00007ffeefbff768: <0x0000000004465cc6  0x000000c0001c6000
0x00007ffeefbff778:  0x00007ffeefbff7e8  0x0000000000000000
0x00007ffeefbff788:  0x00000000047cb720  0x0000000000000000
0x00007ffeefbff798:  0x000000c000187738  0x00000000040ade20 <syscall.libc_getpid_trampoline+0x0000000000000000>
0x00007ffeefbff7a8:  0x00007ffeefbff7f0 !0x00007fff6ca7570a
0x00007ffeefbff7b8: >0x00007ffeefbff7f0  0x0000000004784000
0x00007ffeefbff7c8:  0x000000000000032e  0x00000000041169c5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff7d8:  0x0000000004068bbf <runtime.syscall+0x000000000000001f>  0x000000c0001876f0
0x00007ffeefbff7e8:  0x00007ffeefbff830  0x000000c0001876c0
0x00007ffeefbff7f8:  0x0000000004066a30 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff808:  0x000000c0001a6600  0x6600000000000020
0x00007ffeefbff818:  0x0000000000000000  0x000000c0000001a0
0x00007ffeefbff828:  0x0000000000000968  0x000000c0000001a0
0x00007ffeefbff838:  0x0000000004064b49 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff848:  0x00000000044e0678  0x00000000047cb340
0x00007ffeefbff858:  0x00007ffeefbff8a0  0x0000000004064a45 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff868:  0x00000000040649fd <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/signal_unix.go:719 +0x389

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x41169c0, 0x1, 0x40487413, 0xc000187780)
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc0001876f0 sp=0xc0001876d0 pc=0x406367b
syscall.syscall(0x0, 0x0, 0xe, 0x10000c000194350)
	<autogenerated>:1 +0x26 fp=0xc000187738 sp=0xc0001876f0 pc=0x40693c6
golang.org/x/sys/unix.ioctl(0x18, 0x4c40a68, 0x18)
	/Users/riz/go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc000187768 sp=0xc000187738 pc=0x4116659
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/riz/go/pkg/mod/golang.org/x/sys@v0.0.0-20200223170610-d5e6a3e2c0ae/unix/ioctl.go:63
github.com/mattn/go-isatty.IsTerminal(0x43fb700)
	/Users/riz/go/pkg/mod/github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc0001877d8 sp=0xc000187768 pc=0x42f0f50
github.com/mgutz/logxi/v1.init.0()
	/Users/riz/go/pkg/mod/github.com/mgutz/logxi@v0.0.0-20161027140823-aebf8a7d67ab/v1/init.go:181 +0xdb fp=0xc000187830 sp=0xc0001877d8 pc=0x42f6fdb
runtime.doInit(0x478c620)
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/proc.go:6498 +0x123 fp=0xc000187968 sp=0xc000187830 pc=0x4045863
runtime.doInit(0x478b500)
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc000187aa0 sp=0xc000187968 pc=0x40457b1
runtime.doInit(0x4787180)
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc000187bd8 sp=0xc000187aa0 pc=0x40457b1
runtime.doInit(0x478c7a0)
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc000187d10 sp=0xc000187bd8 pc=0x40457b1
runtime.doInit(0x478de00)
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc000187e48 sp=0xc000187d10 pc=0x40457b1
runtime.doInit(0x478a380)
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc000187f80 sp=0xc000187e48 pc=0x40457b1
runtime.main()
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/proc.go:238 +0x1e6 fp=0xc000187fe0 sp=0xc000187f80 pc=0x4038726
runtime.goexit()
	/usr/local/Cellar/go@1.17/1.17.13/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000187fe8 sp=0xc000187fe0 pc=0x4066d21
monkeyfist:riz  ~>
```

```
monkeyfist:riz  ~> go version
go version go1.16.15 darwin/amd64
monkeyfist:riz  ~> go install -v github.com/apache/mynewt-mcumgr-cli/mcumgr@latest
go: downloading github.com/apache/mynewt-mcumgr-cli v0.0.0-20220314100811-4ca672d31f82
go: downloading mynewt.apache.org/newt v0.0.0-20201028015609-b57111dbd19f
go: downloading mynewt.apache.org/newtmgr v0.0.0-20201028150837-60b2da78788c
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/JuulLabs-OSS/ble v0.0.0-20200716215611-d4fcc9d598bb
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/sirupsen/logrus v1.5.0
go: downloading github.com/joaojeronimo/go-crc16 v0.0.0-20140729130949-59bd0194935e
go: downloading github.com/runtimeco/go-coap v0.0.0-20190911184520-8e5532820fc0
go: downloading github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
go: downloading github.com/JuulLabs-OSS/cbgo v0.0.1
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/spf13/cobra v0.0.5
go: downloading gopkg.in/abiosoft/ishell.v2 v2.0.0
go: downloading gopkg.in/cheggaaa/pb.v1 v1.0.28
go: downloading golang.org/x/net v0.0.0-20191119073136-fc4aabc6c914
go: downloading github.com/ugorji/go v1.1.7
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/abiosoft/readline v0.0.0-20180607040430-155bce2042db
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: downloading github.com/mattn/go-runewidth v0.0.6
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mgutz/logxi v0.0.0-20161027140823-aebf8a7d67ab
go: downloading github.com/raff/goble v0.0.0-20200327175727-d63360dcfd80
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
monkeyfist:riz  ~> mcumgr
mcumgr helps you manage remote devices

Usage:
  mcumgr [flags]
  mcumgr [command]

Available Commands:
  config      Read or write a config value on a device
  conn        Manage mcumgr connection profiles
  crash       Send a crash command to a device
  datetime    Manage datetime on a device
  echo        Send data to a device and display the echoed back data
  fs          Access files on a device
  help        Help about any command
  image       Manage images on a device
  interactive Run mcumgr interactive mode (used for COAP only)
  log         Manage logs on a device
  mpstat      Read mempool statistics from a device
  res         Access a CoAP resource on a device
  reset       Perform a soft reset of a device
  run         Run test procedures on a device
  shell       Execute shell commands remotely
  stat        Read statistics from a device
  taskstat    Read task statistics from a device
  version     Display the mcumgr version number

Flags:
  -c, --conn string         connection profile to use
      --connextra string    Additional key-value pair to append to the connstring
      --connstring string   Connection key-value pairs to use instead of using the profile's connstring
      --conntype string     Connection type to use instead of using the profile's type
  -i, --hci int             HCI index for the controller on Linux machine
  -h, --help                help for mcumgr
  -l, --loglevel string     log level to use (default "info")
      --name string         name of target BLE device; overrides profile setting
      --ompres string       Use this CoAP resource instead of /omgr (default "/omgr")
  -t, --timeout float       timeout in seconds (partial seconds allowed) (default 10)
  -r, --tries int           total number of tries in case of timeout (default 1)
      --write-rsp           Send BLE acked write requests instead of unacked write commands

Use "mcumgr [command] --help" for more information about a command.
monkeyfist:riz  ~>
```

**Comment by sjanc** [comment]
Hi,

Could you check with current master?  I updated some deps few months back (in newtmgr which mcumgr simply wraps) and added CI actions for building on linux, mac and windows.   It seems to build OK there..

https://github.com/apache/mynewt-newtmgr/actions/runs/5749724349/job/15585074182?pr=199
